TITLE = 'Temperature Converter'
TITLE_COLOR = '#f3f3f3'

FONT = 'Calibri'

WINDOW_SIZE = 400
RESIZABLE = False
WINDOW_COLOR = '#c36f6f'

FAHRENHEIT_UNIT = 'F'
KELVIN_UNIT = 'K'
CELSIUS_UNIT = 'C'

FRAME_COLOR = '#f3f3f3'
BUTTON_COLOR = '#b14343'
BUTTON_TEXT_COLOR = '#f3f3f3'
BUTTON_HOVER_COLOR = '#c36f6f'

LARGE_FONT_SIZE = 30
MEDIUM_FONT_SIZE = 20
SMALL_FONT_SIZE = 10

RESULT_COLOR = '#b14343'
CORNER_RADIUS = 10

SMALL_AMOUNT = 0.01
LARGE_AMOUNT = 1
